apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      include /etc/nginx/mime.types;
      server {
        listen 8091;
        index index.html index.htm index.php;
        root  /code;
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_split_path_info ^(.+\.php)(/.+)$; #this line
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
        location ~* \.(js|jpg|png|css)$ {
            root /code;
        }
      }
    }
