apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
     app: nginx-phpfpm
     tier: back-end
spec:
  volumes:
    - name: code
      persistentVolumeClaim:
        claimName: code
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  containers:
    - name: nginx-container
      image: nginx:alpine
      volumeMounts:
        - name: code
          mountPath: /code
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
    - name: php-fpm-container
      image: fernandomaceda/php-fpm
      ports:
      - containerPort: 9000
        name: http
        protocol: TCP
      volumeMounts:
        - name: code
          mountPath: /code
